- name: Allow and rate limit SSH
  community.general.ufw:
    rule: limit
    name: OpenSSH

- name: Install SPADS ufw config
  ansible.builtin.template:
    src: "ufw.spads.j2"
    dest: "/etc/ufw/applications.d/spads"
  notify: "Reload ufw profile configs"

- name: Allow SPADS ports
  community.general.ufw:
    rule: allow
    name: SPADS

- name: Install checkmk ufw config
  ansible.builtin.template:
    src: "ufw.checkmk.j2"
    dest: "/etc/ufw/applications.d/checkmk"
  when: checkmk_monitoring_enabled == true
  notify: "Reload ufw profile configs"

- name: Allow checkmk agent ports
  community.general.ufw:
    rule: limit
    name: Checkmk Agent
  when: checkmk_monitoring_enabled == true

- name: Allow ports for additional services
  community.general.ufw:
    rule: allow
    name: '{{ item }}'
  loop: "{{ ufw_additional_profiles }}"

- name: Ensure default deny for incoming traffic
  community.general.ufw:
    default: deny
    direction: incoming

- name: Enable firewall
  community.general.ufw:
    state: enabled
