- name: Run "apt update"
  ansible.builtin.apt:
    update_cache: yes
  changed_when: false

- name: Run "apt autoremove"
  ansible.builtin.apt:
    autoremove: yes

- name: Run "apt upgrade"
  ansible.builtin.apt:
    name: "*"
    state: latest

- name: Install required packages
  ansible.builtin.package:
    pkg: "{{ package_dependencies }}"

- name: Add the user {{ spads_username }} and append the group 'sudo' to the user's groups
  ansible.builtin.user:
    name: "{{ spads_username }}"
    shell: /bin/bash
    groups: sudo
    password: "{{ spads_user_password }}"
    append: yes

- name: Check if Inline::Python is installed (fails are permitted)
  ansible.builtin.shell:
    cmd: sh /usr/bin/perldoc perllocal | grep Inline::Python
  ignore_errors: true
  register: result
  changed_when: false

- debug: var=result.stdout_lines

- name: Run "cpanm https://github.com/niner/inline-python-pm.git"
  ansible.builtin.command:
    cmd: "cpanm https://github.com/niner/inline-python-pm.git"
  register: out
  when: result is failed

- debug: var=out.stdout_lines
  when: result is failed

- debug: var=out.stdout_lines

- name: Set hostname
  ansible.builtin.hostname:
    name: "spads-{{ inventory_hostname }}"
  tags: container_incompatible

- name: Set /etc/hosts 127.0.2.1 entry with new hostname
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.2\.1'
    line: '127.0.2.1 spads-{{ inventory_hostname }}'
