---
- name: Initial config
  ansible.builtin.import_tasks:
    file: initialSetup.yaml

- name: Configure firewall
  ansible.builtin.import_tasks:
    file: firewall.yaml
  tags: container_incompatible

- name: Configure swap
  ansible.builtin.import_tasks:
    file: swap.yaml
  tags: container_incompatible
  when: configure_swap

- name: Install SPADS
  become: true
  become_user: "{{ spads_username }}"
  ansible.builtin.import_tasks:
    file: installSPADS.yaml

- name: Install map_syncer
  ansible.builtin.import_tasks:
    file: map_syncer.yaml

- name: Configure services
  ansible.builtin.import_tasks:
    file: services.yaml
