- name: Install scripts
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ spads_install_path }}/{{ item }}"
    mode: "0755"
    owner: spads
    group: spads
  with_items:
    - clear_rapid_packages.sh
    - clear_replays.sh

- name: Install systemd service
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}"
    mode: "0644"
  with_items:
    - pr-downloader.service
    - pr-downloader.timer
    - map_syncer.service
    - spads_config_updater.service
    - spads_config_updater.timer
    - spring-setcpuaffinity.service
    - spads.service
    - clear_rapid_packages.service
    - clear_rapid_packages.timer
    - clear_replays.service
    - clear_replays.timer

- name: Force systemd to reread configs
  ansible.builtin.systemd:
    daemon_reload: true
