- name: Copy pr-downloader service template file to remote host
  ansible.builtin.template:
    src: "pr-downloader.service.j2"
    dest: "/etc/systemd/system/pr-downloader.service"

- name: Copy pr-downloader timer template file to remote host
  ansible.builtin.template:
    src: "pr-downloader.timer.j2"
    dest: "/etc/systemd/system/pr-downloader.timer"

- name: Copy map_syncer service template file to remote host
  ansible.builtin.template:
    src: "map_syncer.service.j2"
    dest: "/etc/systemd/system/map_syncer.service"

- name: Copy spads_config_updater service template file to remote host
  ansible.builtin.template:
    src: "spads_config_updater.service.j2"
    dest: "/etc/systemd/system/spads_config_updater.service"

- name: Copy spads_config_updater timer template file to remote host
  ansible.builtin.template:
    src: "spads_config_updater.timer.j2"
    dest: "/etc/systemd/system/spads_config_updater.timer"

- name: Copy spring-setcpuaffinity service template file to remote host
  ansible.builtin.template:
    src: "spring-setcpuaffinity.service.j2"
    dest: "/etc/systemd/system/spring-setcpuaffinity.service"

- name: Copy SPADS service template file to remote host
  ansible.builtin.template:
    src: "spads.service.j2"
    dest: "/etc/systemd/system/spads.service"

- name: Force systemd to reread configs
  ansible.builtin.systemd:
    daemon_reload: true
