- name: Check if swap file exists
  ansible.builtin.stat:
    path: "{{ swap_file }}"
    get_checksum: no
    get_mime: no
  register: swap_file_check

- name: Create swap file
  become: yes
  ansible.builtin.file:
    state: touch
    path: "{{ swap_file }}"
  when: not swap_file_check.stat.exists

- name: Create swap space
  ansible.builtin.command: dd if=/dev/zero of={{ swap_file }} bs=1M count={{ swap_size }}
  when: not swap_file_check.stat.exists

- name: Format swap file
  become: yes
  ansible.builtin.command: mkswap {{ swap_file }}
  when: not swap_file_check.stat.exists

- name: Set permissions on swap file
  become: yes
  ansible.builtin.file:
    path: "{{ swap_file }}"
    mode: 0600

- name: Add to fstab
  become: yes
  ansible.builtin.lineinfile:
    dest: /etc/fstab
    regexp: "^{{ swap_file }}"
    line: "{{ swap_file }} swap swap defaults 0 0"

- name: Turn on swap
  become: yes
  ansible.builtin.command: swapon -a
  changed_when: false

- name: Set swapiness to {{ swap_swappiness }}
  become: yes
  ansible.builtin.sysctl:
    name: vm.swappiness
    value: "{{ swap_swappiness }}"
