- name: Check if swap file exists
  ansible.builtin.stat:
    path: "{{ swap_file }}"
    get_checksum: no
    get_mime: no
  register: swap_file_check

- name: Get current swap file size
  ansible.builtin.command: du -m {{ swap_file }}
  register: swap_file_size
  when: swap_file_check.stat.exists
  changed_when: false

- name: Parse current swap file size
  set_fact:
    current_swap_size: "{{ swap_file_size.stdout.split()[0] | int }}"
  when: swap_file_check.stat.exists

- name: Turn off swap if size is not equal to desired
  become: yes
  ansible.builtin.command: swapoff {{ swap_file }}
  when: swap_file_check.stat.exists and current_swap_size != swap_size

- name: Create or resize swap file
  become: yes
  ansible.builtin.command: dd if=/dev/zero of={{ swap_file }} bs=1M count={{ swap_size }}
  when: not swap_file_check.stat.exists or (swap_file_check.stat.exists and current_swap_size != swap_size)

- name: Format swap file
  become: yes
  ansible.builtin.command: mkswap {{ swap_file }}
  when: not swap_file_check.stat.exists or (swap_file_check.stat.exists and current_swap_size != swap_size)

- name: Set permissions on swap file
  become: yes
  ansible.builtin.file:
    path: "{{ swap_file }}"
    mode: 0600

- name: Add to fstab
  become: yes
  ansible.builtin.lineinfile:
    dest: /etc/fstab
    regexp: "^{{ swap_file }}"
    line: "{{ swap_file }} swap swap defaults 0 0"

- name: Turn on swap
  become: yes
  ansible.builtin.command: swapon -a
  changed_when: false

- name: Set swapiness to {{ swap_swappiness }}
  become: yes
  ansible.builtin.sysctl:
    name: vm.swappiness
    value: "{{ swap_swappiness }}"