---
- name: Restart SPADS
  hosts: all
#  remote_user: root

  tasks:
    - name: Restart SPADS services
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: restarted
      with_items:
        - pr-downloader.service
        - spads_config_updater.service
        - spads.service
        - map_syncer.service

