---
- name: Start SPADS
  hosts: all
  become: yes

  tasks:
    - name: Enable and start SPADS timers and services
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: started
        enabled: true
      with_items:
        - pr-downloader.timer
        - spring-setcpuaffinity.service
        - spads_config_updater.timer
        - map_syncer.service

    - name: Start and enable SPADS
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: started
        enabled: true
      with_items:
        - spads.service
