---
- name: Stop SPADS
  hosts: all
  become: yes

  tasks:
    - name: Stop and disable SPADS timers and services
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: stopped
        enabled: false
      with_items:
        - pr-downloader.timer
        - rclone-maps.timer
        - spads_config_updater.timer
        - pr-downloader.service
        - rclone-maps.service
        - spads_config_updater.service

    - name: Stop and disable SPADS
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: stopped
        enabled: false
      with_items:
        - spads.service
