
spads_username: "{{ vault_spads_username }}"
spads_user_password: "{{ vault_spads_user_password }}"
# if running SPADS as root then user_homedir needs to be /root
user_homedir: /home/{{ spads_username }}
spads_install_path: "{{ user_homedir }}/spads"

# skips the tasks in the delete.yaml playbook if false as a safety mechanism
allow_delete: false

sftp_login: "{{ vault_sftp_login }}"
sftp_password: "{{ vault_sftp_password }}"

# Important: The URL's for engine releases contain %7B characters for brackets. It seems that wget does not always like these, so replace with {}
# Note that these characters get replaced with '.' characters for the engine_dir
engine_github_path: https://github.com/beyond-all-reason/spring/releases/download/spring_bar_{BAR105}105.1.1-2152-gb91f41c/spring_bar_.BAR105.105.1.1-2152-gb91f41c_linux-64-minimal-portable.7z
engine_dir: spring_bar_.BAR105.105.1.1-2152-gb91f41c_linux-64-minimal-portable


# allows system monitoring, currently with checkmk
checkmk_monitoring_enabled: true
checkmk_monitoring_port: 6556

# allows to enable additonal services on the per-host basis
ufw_additional_profiles: []

package_dependencies:
  - acl
  - byobu
  - cpanminus
  - curl
  - g++
  - git
  - htop
  - libdbd-sqlite3-perl
  - libffi-platypus-perl
  - locate
  - lsof
  - make
  - mc
  - p7zip
  - p7zip-full
  - perl-doc
  - procps
  - python3-dev
  - python3-distutils
  - sshpass
  - sudo
  - swig
  - ufw
  - wget

# swap size in megabytes
configure_swap: yes
swap_size: 4096
swap_file: /var/swap.img
swap_swappiness: '10'

# the following are for spads_cluster_launcher.sh
spads_lobbyLogin: '[teh]cluster1'
spads_channel:
spads_lobbyPassword: "{{ vault_spads_lobbyPassword }}"
spads_registrationEmail: "{{ vault_spads_registrationEmail }}"
spads_lobbyHost: server4.beyondallreason.info
spads_baseGamePort: 53200
spads_baseAutoHostPort: 53100
spads_hostRegion: '"UNKNOWN - "'  # To be better defined in per group vars
spads_enginesBaseDir: "{{ spads_install_path }}/var/spring/"
spads_engineDir: "{{ engine_dir }}/"
spads_springDataDir: "{{ spads_install_path }}/var/spring/data"
spads_endGameCommandPath: "{{ spads_install_path }}/upload_replay.sh"
spads_localLanIp: 192.168.1.102
spads_maxInstances: 99
spads_targetSpares: 1
spads_clusters:
spads_hostIp:
spads_autoLoadPlugins: '"AutoRegister;ClusterManager;JsonStatus;InGameMute;DynamicMapRotation;BarManager;RatingManager"'

# the following are for spadsInstaller.auto
autoinstaller_release: unstable
autoinstaller_etcDir: etc
autoinstaller_varDir: var
autoinstaller_logDir: log
autoinstaller_springBinariesType: custom
autoinstaller_unitsyncPath: "{{ spads_install_path }}/var/spring/{{ engine_dir }}/libunitsync.so"
autoinstaller_baseDataDir: "{{ spads_install_path }}/var/spring/{{ engine_dir }}"
autoinstaller_mapModDataDir: "{{ spads_install_path }}/var/spring/"
autoinstaller_springServerType: dedicated
autoinstaller_springServer: "{{ spads_install_path }}/var/spring/{{ engine_dir }}/spring-dedicated"
autoinstaller_modName: "_NO_GAME_FOUND_"
autoinstaller_lobbyLogin: "[teh]cluster"
autoinstaller_lobbyPassword: changeme
autoinstaller_owner: changeme

mapSyncer_mqttBroker: broker.hivemq.com
mapSyncer_healthcheckUrl: https://hc-ping.com/{{ vault_healthchecksioPingKey }}/spads-{{ inventory_hostname }}-maps-sync
