spads_user_password: "{{ vault_spads_user_password }}"

sftp_login: "{{ vault_sftp_login }}"
sftp_password: "{{ vault_sftp_password }}"

# allows system monitoring, currently with checkmk
checkmk_monitoring_enabled: true
checkmk_monitoring_port: 6556

# swap size in megabytes
configure_swap: yes
swap_size: 4096
swap_file: /var/swap.img
swap_swappiness: '10'

spads_lobbyPassword: "{{ vault_spads_lobbyPassword }}"
spads_registrationEmail: "{{ vault_spads_registrationEmail }}"
spads_lobbyHost: server4.beyondallreason.info

mapSyncer_healthcheckUrl: https://hc-ping.com/{{ vault_healthchecksioPingKey }}/spads-{{ inventory_hostname }}-maps-sync

configure_zabbix_agent: true
zabbix_psk: "{{ vault_zabbix_psk }}"
zabbix_server: 192.3.148.174
